@startuml
object "Client"
object "Worker"
object "Studio"
object "Appointment"
object "Service"
object "Material"
object "MaterialService"

"MaterialService" *-- "Material"
"Service" *-- "MaterialService"
"Appointment" *-- "Client"
"Appointment" *-- "Worker"
"Worker" *-- "Studio"
"Appointment" *-- "Studio"
"Appointment" *-- "Service"
@enduml