@startuml
|User|
start
:Enters system;
:Asks for client info;
:"Client info request";

|System|
:Processes search request;
:Checks for current state;
:"Client info";

|User|
:Client info;
:Updates client info;
:"Client info update request";

|System|
:Stores client info;
:Generates updated data;
:"Updated data";

|User|
:Reviews updated data;
stop
@enduml
